/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as homeIndexRouteImport } from "./routes/(home)/index"
import { Route as AboutIndexRouteImport } from "./routes/about/index"
import { Route as ProjectsIndexRouteImport } from "./routes/projects/index"

const homeIndexRoute = homeIndexRouteImport.update({
  id: "/(home)/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: "/about/",
  path: "/about/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: "/projects/",
  path: "/projects/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof homeIndexRoute
  "/about/": typeof AboutIndexRoute
  "/projects/": typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof homeIndexRoute
  "/about": typeof AboutIndexRoute
  "/projects": typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/(home)/": typeof homeIndexRoute
  "/about/": typeof AboutIndexRoute
  "/projects/": typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/about/" | "/projects/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/about" | "/projects"
  id: "__root__" | "/(home)/" | "/about/" | "/projects/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeIndexRoute: typeof homeIndexRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(home)/": {
      id: "/(home)/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/about/": {
      id: "/about/"
      path: "/about"
      fullPath: "/about/"
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/projects/": {
      id: "/projects/"
      path: "/projects"
      fullPath: "/projects/"
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  homeIndexRoute: homeIndexRoute,
  AboutIndexRoute: AboutIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
